version: "2.1"
services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DBMS_IP=mysql
      - DBMS_PORT=3306
      - DBMS_USER=root
      - DBMS_PASS=123
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    container_name: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=123
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
